// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANlyc0x0aYchtet8TLfxKqM-T0azDXldA',
    appId: '1:535906956056:web:b23e1971d1e5500bc6646d',
    messagingSenderId: '535906956056',
    projectId: 'reddict1',
    authDomain: 'reddict1.firebaseapp.com',
    storageBucket: 'reddict1.appspot.com',
    measurementId: 'G-N7S94KWDN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCT8KC3AjwiY98m5IHaTNvVmbrzV9_6YI',
    appId: '1:535906956056:android:5a200a1a3c2eff18c6646d',
    messagingSenderId: '535906956056',
    projectId: 'reddict1',
    storageBucket: 'reddict1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7KZki-Mbibg56u6fHp6XCX0MbmC3nh9c',
    appId: '1:535906956056:ios:180d07daea1a5a88c6646d',
    messagingSenderId: '535906956056',
    projectId: 'reddict1',
    storageBucket: 'reddict1.appspot.com',
    iosBundleId: 'com.example.reddict1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7KZki-Mbibg56u6fHp6XCX0MbmC3nh9c',
    appId: '1:535906956056:ios:a1a741652eedc623c6646d',
    messagingSenderId: '535906956056',
    projectId: 'reddict1',
    storageBucket: 'reddict1.appspot.com',
    iosBundleId: 'com.example.reddict1.RunnerTests',
  );
}
